### ISSUE TITLE
Elect OCI TOB Chair 2024

### ISSUE THREAD

**Issue by amye** [opencontainers/tob#143]
The @opencontainers/tob needs to elect a new chair for 2024!

Is anyone from the @opencontainers/tob interested in running?

@samuelkarp would you like to stand again?

**Comment by cyphar** [comment]
I'll throw my hat in the ring too.

**Comment by samuelkarp** [comment]
I'd be happy to serve again.

**Comment by sudo-bmitch** [comment]
Oh wow, if we're going to make this an election this year, I guess I can run too.

**Comment by amye** [comment]
Election it is! 

> i. The TOB shall elect a TOB Chair. The nominee with the most votes from the TOB members shall win the Chair position for a term of one (1) year. In the event of a tie vote, a random selection process (e.g. coin toss) shall be used to determine the winner. The TOB Chair shall have the responsibility to call meetings of the TOB and set TOB meeting agendas with input from TOB members. 

Here's a rough timeline: 
* Nomination period: Jan 29-Jan 31st
* Ballots will be distributed through [CIVS](https://civs.cs.cornell.edu/) to the TOB members, election will run using the Condorcet-IRV method. 
* Voting period from Feb 1 - Feb 8th, election to complete at 10am Pacific on Thursday, Feb 8th. 

Just in time for the OCI dev call on Thursday and this gets us underway for the year.
Happy to hear objections!

**Comment by amye** [comment]
Final call on nominations, the election kicks off at noon Pacific today 👍

**Comment by cyphar** [comment]
If we're doing election pledges, I'll say that my goal would be to finish off the Charter improvements we started working on a few years ago but never got across the finish line. I'm not sure how much interest there is in going through legal review for an updated Charter but there were several issues we found with the current Charter that we should address in some form (whether that means coming to informal agreements or having actual Charter changes). I opened a few PRs to the Charter at the time, I'll have to read through them again to refresh my memory on the exact issues we had...

**Comment by amye** [comment]
(Honestly we can do that regardless of who is chair) - but yes! Conversation in here is highly welcome!

**Comment by samuelkarp** [comment]
I'm a bit late for a statement here, but: I'm happy to continue to serve as chair if the other TOB members want me to.  My view of the chair's role is as a facilitator rather than a leader; the Chair is not more important than other members of the TOB and not the only person who can drive things forward.

In light of the above, I don't have any specific goals or promises to make other than to be present, available, and helpful for facilitating forward progress.

Unrelated to the above, just wanted to clarify a few things that @cyphar and @amye brought up:

> Honestly we can do that regardless of who is chair)

:100:, there's nothing magical about the role of the chair here.  We can (and should) revisit the amendment proposals regardless of who is chair.

> and the only person who can call meetings is the chair.

Charter section 6. j. enumerates the conditions where a meeting is called.  6. j. iii. is a chair-called meeting (and anyone can _ask_ the chair to call a meeting too; I'm certainly happy to whenever), while 6. j. i. is a TDC-requested TOB meeting and 6. j. ii. is a 2/3 TOB vote for a meeting.

**Comment by sudo-bmitch** [comment]
My platform is a bit of an anti-platform. There's no need to vote for me, because the others running would also make a great chair and I'm very happy to work with each of them. If elected, I'm happy to call meetings of the TOB if asked, just send over a request and we can make it happen. Hopefully my participation in the weekly developer meetings gives everyone an idea of my willingness to hold meetings and guide them as needed. When possible, I also think it's good to make decisions async to be accommodating to those with busy schedules and different timezones.

The things I feel the TOB should be working on this year, regardless of who is chair, is working through our backlogged issues, and resolving conflicts in the TDC that are escalated to us following 5.b.xv:

> Referring to the Technical Oversight Board any issues that deal with failure to follow established technical governance, issues that impact multiple OCI Projects or specifications, or conflicts that cannot be resolved within the TDC. Issues shall be referred to the TOB according to the requirements in Section 6

Given the delays from the image-spec and distribution-spec groups in making a 1.1.0 release and resolving disputes this past year, I feel there is a possibility of those disputes being escalated to the TOB, and I believe we should be responsive to any escalations.

**Comment by amye** [comment]
Samuel Karp is our returning TOB chair!
