### ISSUE TITLE
Distribution Specification

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#34]
At the OCI F2F (https://docs.google.com/document/d/1rL4wiY6Q7R199wz0PBtbbPVjMo_3v2BpO6c1kItPTLw/edit), we discussed kicking off a distribution specification project, based on the Docker distribution spec: https://twitter.com/chanezon/status/938845534466596864

We will have to go through the official OCI channels, which involves a project proposal to the @opencontainers/tob.

**Comment by caniszczyk** [comment]
Docker distribution spec: https://github.com/docker/distribution/tree/master/docs/spec

**Comment by wking** [comment]
It looks like @xiekeyang mentioned oci-discovery [1] in the F2F.  And
@cyphar also has some work in this space with parcel [2].  Both of
those cover discovery and distribution (although oci-discovery has
protocol registries for ref and CAS engines [3,4]).

Also in the F2F minutes, @dmcgowan also pointed out a distinction
between *discovery* and a registry (e.g. see [5], where
oci-discovery's OCI Well-Known URI Ref-Engine Discovery protocol lets
an authority say “look up my images in this Docker registry”).  Is
this initial distribution work going focused only on a registry
protocol, or is it also interested in discovery?  From the F2F, it
sounds like @vbatts wants to focus on the registry, and continue to
punt on discovery?

[1]: https://github.com/xiekeyang/oci-discovery
[2]: https://github.com/cyphar/parcel
[3]: https://github.com/xiekeyang/oci-discovery/blob/6870be0b85b4615f10433b5d4aa33bd6246ca912/ref-engine-protocols.md
[4]: https://github.com/xiekeyang/oci-discovery/blob/6870be0b85b4615f10433b5d4aa33bd6246ca912/cas-engine-protocols.md
[5]: https://github.com/xiekeyang/oci-discovery/blob/6870be0b85b4615f10433b5d4aa33bd6246ca912/well-known-uri-ref-engine-discovery.md#example-1

**Comment by dmcgowan** [comment]
> From the F2F, it sounds like @vbatts wants to focus on the registry, and continue to
punt on discovery?

@wking the conversation was around standardizing the registry protocol since it already the defacto standard and avoid using the standardization process for innovating on new protocols. Innovation on discovery can handle in tandem to standardization of the registry protocol and added later. My point was that discovery and registry are completely separate and do not need to be added together. Also keep in mind that while all existing clients today are using the registry protocol, there is no common way in which discovery is being done.  In this case discovery should not require any changes to the existing registry protocol or implementations.

**Comment by wking** [comment]
> @wking the conversation was around standardizing the registry protocol since it already the defacto standard and avoid using the standardization process for innovating on new protocols.

That makes sense.  The risk with specifying after getting widespread adoption is that you can't fix things anymore because the backward-compat cost is too high (like [this][1] and opencontainers/image-spec#24).  And the risk with specifying before widespread adoption is that you don't know what needs fixing.  Either way, the solution is to eventually cut a v2 spec, and that's fine.
  
[1]: https://github.com/opencontainers/image-spec/blame/v1.0.0/manifest.md#L18-L26

**Comment by caniszczyk** [comment]
As a heads up @opencontainers/tob, here's a draft proposal for the distribution spec project: https://docs.google.com/document/d/15y0SBrrDFIEM7pnU-Oe3Y6pq-eTZfo0mk-k33cS2hR4/edit#heading=h.fs1oc6z7su0d

We will let it simmer for a week or so to gather feedback before formalizing things on GitHub.

**Comment by caniszczyk** [comment]
minutes from the last OCI Dev meeting regarding the distribution spec: http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2018/opencontainers.2018-01-10-22.01.html

The plan is to work together on a proposal and present it to the TOB for vote, current thinking is that it won't be ready until after the TOB election on Jan 29th.

**Comment by caniszczyk** [comment]
The google doc has been open long enough and seems baked. I converted it to markdown and opened up a PR so we can continue/finalize the discussion there for a couple of weeks or so and than formalize a vote after the new @opencontainers/tob is formed: https://github.com/opencontainers/tob/pull/35

**Comment by caniszczyk** [comment]
Just an update here, now that the new @opencontainers/tob is elected, I will be working on updating the proposal to get it in shape for a vote some time next month. Let me know if there are any concerns about the timeline.

**Comment by caniszczyk** [comment]
I kicked off the official project creation vote here for the OCI TOB to approve:

https://groups.google.com/a/opencontainers.org/forum/#!topic/tob/dU6uXM__ilU

**Comment by caniszczyk** [comment]
CREATED!

https://www.opencontainers.org/announcement/2018/04/09/oci-announces-dist-spec-project
