### ISSUE TITLE
Create icon set for containers and artifacts

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#65]
@SteveLasker has suggested it would be great to have standardized icons for container related things, OCI is happy to fund this work, here are some things suggested to iconify:

* Public container registry
* Private container registry
* Image – at rest
* Container - instanced
* SBOM (software bill of materials)
* Source artifact, similar to the gpl requirements to have source alongside the binary
* A policy manager, like OPA
* An orchestrator, like kubernetes

We should be wary about any overlap with the kubernetes stencil set: https://github.com/kubernetes/community/tree/master/icons

**Comment by SteveLasker** [comment]
To put some additional context, I was writing up some e2e scenarios for the Notary v2 spec, and struggled with how to include imagery that:
- wasn't tied to a cloud or vendor
- wasn't tied to a specific project as I wanted to reference many of these things generically
- wouldn't solicit attacks for not posting vendor/project, trademarked content.

![image](https://user-images.githubusercontent.com/7647382/74383484-24776080-4da4-11ea-9754-b3c006f543aa.png)

By creating a set of OSS, free to share, use, etc., all of us that present at public events, work in the OSS space, will have a set of images we can use generically that legal departments can't complain about.  

Here's a bit larger list. Please add comments for additional icons we should consider.

- Api
- Authentication
- Cloud
- Container
- Container host
- Customer
- Database
- Developer
- Distribution/registry
- Doc db
- File
- Firewall
- Firewall rrule
- Function
- Image
- Key
- On-prem
- Orchestrator
- Orchestrator, (kubernetes, but   could also represent ecs, gce, aks, …)
- Policy enforcement/management
- Policy manager (like OPA)
- SBOM (software bill of   materials)
- Scheduled job
- Security scanning
- Signature
- Source artifact (similar to   the gpl requirements to have source alongside the binary)
- Storage
- Testing
- Vm
- Vnet
- Web

**Comment by SteveLasker** [comment]
Adding a few more
Some references: 
- [Microsoft Azure Cloud Icons](https://www.microsoft.com/en-us/download/details.aspx?id=41937)
- [AWS Icons](https://aws.amazon.com/architecture/icons/)
- [GCP Icons](https://cloud.google.com/icons)

**Comment by caniszczyk** [comment]
[OCI_Icons_V1.zip](https://github.com/opencontainers/tob/files/4329230/OCI_Icons_V1.zip)

Hey @SteveLasker any feedback on these?

**Comment by SteveLasker** [comment]
These are great. 
- Config looks great, `configservice.png` looks like a hammer held by a hand. Is there a general "service" icon that could be used across the specific types of services. The hand in`service.png` seems like a good start. 
- `debugging.png` - l laughed at first. This looks a bit more like closing or fixing bugs. Where "debugging" is more a developer laptop and code, with logs or a breakpoint... Maybe a spin of `developer.png`
- `distribution.png` - the intended reference was more about the OCI Distribution spec/implementation of a registry. 
- `firewallrule.png` - The bang looks a bit like a block/violation, which could also be good. I wonder if the `firewall.png` with a ruler would be too literal?
- `keyvault.png` - nailed it
- `legacymaninframe.png` - chuckled at the crown, awesome!
- `onprem.png` - nice!
- `orchestratork8.png` - On 2nd thought, I wonder if we want this one. Only because we have k8s logos, these were more generic and I wouldn't want to take away from the standard k8s icons. 
- `pipeline.png` could we make this one a bit more straight? Vertical or horizontal. We typically think of a pipeline as steps where things happen between stages of the pipeline. 
- `sbom.png` - seems a bit too generic. Since SBoM is a generic reference, as opposed to a specific project, I wonder if we could do a document icon with SBoM text in the middle?
- `securityscanning.png` - I like the "radar scan" imagery. Could we adorn this with a generic security icon that's consistent across the security icons? 
- `signature.png` - I first saw a kite. 
A thought. As these are so generic, which is good, do we want a version with a bit of text below each one to help identify them? People using the icons could use the version with or without the text. When making presentations, using actual text is crisp, but scaling makes it harder. Just a discussion point.

**Comment by caniszczyk** [comment]
[opencontainerinitiative_icons_V2.pdf](https://github.com/opencontainers/tob/files/4383085/opencontainerinitiative_icons_V2.pdf)

Here's a new version @SteveLasker, what do you think :)? cc: @opencontainers/tob

**Comment by crosbymichael** [comment]
LGTM

**Comment by estesp** [comment]
v2 looks good; I think most of Steve's feedback is addressed, and I'm pretty happy with them. The only one that I still think could use some work is the pipeline.. a google image search on the term ["continuous integration pipeline"](https://www.google.com/search?q=continuous+integration+pipeline) is a good reference for the kind of imagery that I think makes sense; something that connects "steps" with arrows showing a directional flow.

**Comment by mikebrow** [comment]
LGTM

**Comment by SteveLasker** [comment]
All the updates look great, with the one consistent feedback to Phils for the pipeline. When we think of a "pipeline", we think of stages that can be swapped out. I wonder if we could do a set of vertical pipe segments, where a valve shoots off to the right. The idea is one of the vertical segments is swapped out with another type. Here's an example: https://www.onlinewebfonts.com/icon/299075 Perhaps crop the top part, and not represent pipes as far to the right.
Thanks for the great iterations.

**Comment by jdolitsky** [comment]
Lgtm. I'm personally a fan of this one:

<img width="206" alt="Screen Shot 2020-03-25 at 7 01 03 PM" src="https://user-images.githubusercontent.com/393494/77596843-20724e80-6ecb-11ea-814a-7990cc62c836.png">

**Comment by vbatts** [comment]
the `f(x)` is a missing an 'n' as "fuction"

Otherwise LGTM

**Comment by h-vetinari** [comment]
That's a lot of great logos! If I may comment as an outsider, I find the visual language of *container image* and *container host* suboptimal though. Considering the amount of creativity (e.g. for *firewall rule*), I think that *container image* could be the container logo plus a camera, for example?

For *container host*, I could imagine something along the lines of looking into the loading bay of a plane, and seeing (with perspective) containers on the left and right "wall".

**Comment by h-vetinari** [comment]
> @h-vetinari: For container host, I could imagine something along the lines of looking into the loading bay of a plane, and seeing (with perspective) containers on the left and right "wall".

In case this is not clear, here's roughtly what I had in mind (just a quick sketch, not with the corrugated container "look", and loads of other things to improve): 
![container_host](https://user-images.githubusercontent.com/33685575/77648347-4e59a080-6f68-11ea-9695-edf76b826f49.png)

**Comment by fuweid** [comment]
LGTM

**Comment by caniszczyk** [comment]
@SteveLasker you have an example of the pipeline you like? your link 404's

**Comment by SteveLasker** [comment]
![image](https://user-images.githubusercontent.com/7647382/77795163-567a1480-702a-11ea-96c5-9cc220ce8a33.png)
Just a rough idea

**Comment by caniszczyk** [comment]
Ok, FINAL CALL for comments in the next 72 hours :)

[opencontainerinitiative_icons_V4.pdf](https://github.com/opencontainers/tob/files/4404513/opencontainerinitiative_icons_V4.pdf)

**Comment by h-vetinari** [comment]
> @caniszczyk: Ok, FINAL CALL for comments in the next 72 hours :)
>
> [opencontainerinitiative_icons_V4.pdf](https://github.com/opencontainers/tob/files/4404513/opencontainerinitiative_icons_V4.pdf)

Awesome, I really appreciate that you took on my feedback! As another purely optional remark, I still want to re-suggest a solution to what I [perceived](https://github.com/opencontainers/tob/issues/65#issuecomment-604400766) to be a suboptimal `container image` logo:

![container_image](https://user-images.githubusercontent.com/33685575/77949455-42067800-72c7-11ea-99f4-1f289c5d39d7.png)

I think it would be advantageous to reuse the same visual component as for the container (considering how closely related a container and its image are), and I would consider this more easily digestible than the current draft.

PS. again, just a rough sketch; camera logo taken from [here](https://www.flaticon.com/free-icon/dslr-camera_83574?term=dslr%20camera&page=1&position=16))
PPS. If it helps, I can send you the GIMP xcf-file I used to sketch this.

**Comment by SteveLasker** [comment]
Since OCI is the vendor agnostic body, having OCI icons makes sense.  
For image, vs. container. would a film strip, with the holes above/below be too quirky?

**Comment by h-vetinari** [comment]
Great idea! Even easier visually!

**Comment by caniszczyk** [comment]
There's been enough feedback on this, we have posted all the icons here: https://github.com/opencontainers/artwork#oci-icons

Thanks all!
