### ISSUE TITLE
Audit of active maintainers + call for new maintainers

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#95]
@amye and I will work in tandem with the @opencontainers/tob to audit the current list of maintainers.

We will make recommendations based on the data we present to the TOB :)

- [ ] image-spec: https://github.com/opencontainers/image-spec/issues/834
- [ ] runtime-spec: https://github.com/opencontainers/runtime-spec/issues/1101
- [ ] distribution-spec: https://github.com/opencontainers/distribution-spec/issues/262
- [ ] runc: https://github.com/opencontainers/runc/issues/2891

**Comment by jonjohnsonjr** [comment]
Per the dev mailing list:

> If you contribute and would like to become a maintainer, let us know on that issue.

I am interested in becoming a maintainer for both image-spec and distribution-spec.

Looking through the git logs, I have not actually landed any commits in the image-spec repository, but I think that's largely due to the same reason this issue exists :)

While I do have a small number of commits in the distribution-spec, most of my contributions to both projects have been providing guidance and feedback, while wearing many different hats.

I am happy to provide references or justification of my credentials, but I think everyone involved in both projects is pretty familiar with me and my work. If that's not the case, let me know.

**Comment by tych0** [comment]
(Missed the call yesterday because of fires burning :D) I'm happy to participate as a maintainer in image-spec if it is useful. I'm already doing work on umoci, so hopefully some of that context will translate.

**Comment by vrothberg** [comment]
I want to offer help for the image-spec as well.  I'm co-maintainer of [containers/image](https://github.com/containers/image) and most other projects in github.com/containers (Podman, Buildah, Skopeo, etc.).  So far, I've not yet managed to join the calls; I am based in the EU and the weekly calls are too late (11PM) for my brain to function properly.

Would you consider alternating the times of the weekly call?  That may encourage more contributions from folks close to my time zone.

I am supportive of adding both, @jonjohnsonjr and @tych0.  IMHO they have extraordinary technical and communication skills and are a pleasure to work with.

**Comment by ImJasonH** [comment]
Definitely excited to have more active maintainers.

I was excited that we'd seemed to have settled on a rough consensus about https://github.com/opencontainers/image-spec/pull/822 after a month or so of discussion, only to find out that the approvers were in another castle. Even something as simple as https://github.com/opencontainers/image-spec/pull/832 is blocked waiting for a second approver.

I'm also happy to throw my hat in the ring for image-spec, and maybe distribution-spec. I'm fairly new to the community, but I have some years of experience with container images and registries (long-time bikeshed admirer, aspiring bikeshed Picasso). I co-founded [Google Cloud Build](https://cloud.google.com/cloud-build) and [Tekton](https://tekton.dev), and have contributed to [kaniko](https://github.com/GoogleContainerTools/kaniko), [ko](https://github.com/google/ko), [distroless](https://github.com/GoogleContainerTools/distroless), [buildpacks](https://buildpacks.io), [go-containerregistry](https://github.com/google/go-containerregistry), and probably some others I'm forgetting or too ashamed of. I built https://kontain.me for fun, which should give you an idea of what I consider "fun". Jon says I run the most number of registries on the planet, so long as you don't count by QPS 🤣 

Either way, I'll be happy to see renewed attention among maintainers, however that shakes out.

**Comment by caniszczyk** [comment]
We put together a quick spreadsheet of audited maintainers:
https://docs.google.com/spreadsheets/d/1MxaS46oKWdiRIlFRJkN95yIasadhdRoj5Ioo9GDovOE/edit#gid=19082117

We used the simple metric of "active" as a commit in the last 2 years, most of the projects are actually fine, image-spec by far has low active maintainers and needs some folks to step down and/or join the ranks.

**Comment by SteveLasker** [comment]
Please add me to the list of folks looking to become maintainers for image-spec and distribution spec. 
The goal of artifacts was to extend the capabilities of distribution: [OCI Artifacts and a View of the Future](https://stevelasker.blog/2019/08/25/oci-artifacts-and-a-view-of-the-future/) 
Whether artifacts gets merged into distribution or we continue to keep them separate, I'm interested to see the standards expand, including the enablement of the image-spec to evolve for oci-image v2 goals.

**Comment by rchincha** [comment]
Interested in being a maintainer for distribution-spec. Pls. add me to the list if it is useful. Don't have any actual commits to dist-spec project itself, but have been involved with the review process and the zot project.

**Comment by fuweid** [comment]
I’m interested in being a maintainer for runC, even if I just have one commit :p. I’m working on containerD and focus on the runtime. Please add me into the list if it is useful :).

**Comment by amouat** [comment]
I'd be interested in being a maintainer on distribution spec. It looks like you might have enough volunteers already though. I'll try to join the call tonight but I do in general have the same problem as @vrothberg - I would second his suggestion for alternating the call times.

I'm currently working on the Trow registry https://github.com/containersolutions/trow. I have attended several meetings and contributed on the issue tracker in the past. I work for Container Solutions, who have been involved with the development of containers and Kubernetes almost since the start (we helped put on the first DockerCon EU!).

**Comment by tao12345666333** [comment]
I am interested in becoming a maintainer for runC. I am mainly active in runtime projects such as Docker and containerd, and I have also studied some code of runC. Next I will be active in the runC code repository.  Please add me into the list if it is useful 🐱

**Comment by vbatts** [comment]
this has settled down. and while there is always a need for fully active maintainers, there is traction in the projects. 
Closing this particular tracker for now.
